# Makefile.deps created Sun Apr 26 21:09:56 PDT 2015 by make
astree.o: astree.cpp astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp lyutils.h astree.h auxlib.h yyparse.h
auxlib.o: auxlib.cpp auxlib.h
stringset.o: stringset.cpp stringset.h
cppstrtok.o: cppstrtok.cpp auxlib.h stringset.h lyutils.h astree.h \
 yyparse.h
yylex.o: yylex.cpp auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h auxlib.h yyparse.h
